### ISSUE TITLE
responding to rendering delays -- need to delay appearance of the download instructions

### ISSUE THREAD

**Issue by vjcitn** [LiNk-NY/AnnotationHubShiny#3]
I just revisited this  -- I think, at least when visiting after a long delay in server use, there is a substantial interval before the table renders, that is a little confusing -- we immediately see the nice download instructions but no data.  So I'd suggest using a tabPanel so that the download advice is hidden (on second tab) and front panel informs that rendering is ongoing.  I will try to fashion a PR after some experimenting.

**Comment by LiNk-NY** [comment]
Thanks Vince https://github.com/LiNk-NY/AnnotationHubShiny/pull/6
