### ISSUE TITLE
odd behavior of datatable?

### ISSUE THREAD

**Issue by vjcitn** [LiNk-NY/AnnotationHubShiny#4]
when i type in 'hg38' in the box under genome, i just see an x ... could it be an issue of field width?

<img width="1331" alt="ahsx" src="https://user-images.githubusercontent.com/4624066/132990526-c84b64de-6e57-4709-8685-36c06d2483ad.png">

**Comment by LiNk-NY** [comment]
Hi Vince, @vjcitn 

This seems to be an issue when the browser page is made larger with <kbd> Ctrl </kbd> + <kbd> + </kbd>. 
If you do <kbd> Ctrl </kbd> + <kbd> 0 </kbd> the text should be visible. 

Best regards,
Marcel
