### ISSUE TITLE
need shinytoastr popups

### ISSUE THREAD

**Issue by vjcitn** [LiNk-NY/AnnotationHubShiny#7]
the first hit to the server can take a long time to return data.  maybe add a
shiny toastr notification so that visitors don't give up?

**Comment by LiNk-NY** [comment]
Hi Vince, @vjcitn 
Thanks for pointing this out. 
There is an implementation of the `shinytoastr` functionality. 
When I browse to the shiny app, I can see there is a bit of a lag. 
It shows "retrieving AnnotationHub..." and then "done."
Perhaps the "done." is a bit premature and there should be an intermediate message that says "loading AnnotationHub resources...". 
I can look into this.

**Comment by LiNk-NY** [comment]
I've updated the shinytoastr calls so that the loading times appear more natural. 
Thanks. 
https://shiny.sph.cuny.edu/AnnotationHubShiny/
